sudo: required
services:
    - docker

before_install:
    - docker build -t josejames/react-test  -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true josejames/react-test npm run test

after_success:
    - docker build -t josejames/multi-client ./client
    - docker build -t josejames/multi-nginx ./nginx
    - docker build -t josejames/multi-server ./server
    - docker build -t josejames/multi-worker ./worker
    #Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push josejames/multi-client
    - docker push josejames/multi-nginx
    - docker push josejames/multi-server
    - docker push josejames/multi-worker


